---
title: "Primeiros Passos Data Science"
format:
  html:
    theme: journal
---


## Apresentação:

O projeto Ciência de Dados na Educação Pública tem desenvolvido atividades 
que exigem a utilização de diversas ferramentas aplicadas à área de ciência 
de dados. A cada semestre é realizado um pequeno treinamento que permite 
que os novos integrantes sejam recepicionados dentro da metodologia 
do projeto e ao mesmo tempo tornem-se autônomos no desenvolvimento de 
organização de dados, visualização e transformação em materiais didáticos. 
O curso é aberto a participantes de graduação e pós-graduação interessados 
em iniciar na área de tecnologia.

## Objetivo:

Desenvolver habilidades no uso de ferramentas de consulta, manipulação e 
transformação de dados para produção de materiais didáticos e divulgação de 
dados referentes ao site (re)conhecendo Salvador.


## Conteúdos 

- Git: *git init*,*git add*, *git commit -m*, *git checkout*, *git merge*, 
*git status*, *git log*, *git pull*, *git pull request*, *git push*, *git fetch*.
- Github: *Criação de conta do Github*
- Instalação do *R* e *Rstudio*
- Instalação *Vscode*
- Configuração da conta do *Github* no *Rstudio* e *Vscode*
- MySQL: *SHOW DATABASES*, *USE*, *DESCRIBE*, *INSERT INTO*, *SELECT*, *FROM*, *WHERE*
- Instalação *MySQL* e *Workbench*
- Conexão Banco: *R* e *Python*
- Tidyverse: *readr*, *dplyr* *(select(),filter(),group_by(),summarise(),mutate())*, *tidyr* *(gather(),spread())*, *lubridate*, *ggplot2* *(geom_bar(),geom_col())*
- Python: *Vscode*/*Colab*/*Jupyter*,**Pandas*,*Numpy*,*read_csv(...,chuncksize=...)*  


## Datas 

 - Github  (Instlacao git, definição de versionamento, uso no cmd, comandos principais) [Laio/Robson - 18/07]
 - Instalacao R e Rstudio [Laio/Robson - 18/07]
 - SQL/MySQL - [19/07 - Cedma/Aline/Robson]
 - Pacote Tydiverse (dplyr,ggplot2,tidyr,lubridate) [20/07 - Bruna/William]
 - Python/Pandas/chuncks (Robson/Laio(python)* 21/07)
 - Mapas/Leaflet/QGIS [Robson/Elicelma 22/07]

## Instrutores

 - Laio Luis Barbosa Ribeiro 
 - 


## Atividades:

Após a realização do curso *Primeiros Passos Data Science*, os 
participantes serão acompanhados por mais 1 semana de suporte 
para desenvolver um pequeno relatório de uma das escolas participantes 
do projeto *Ciência de Dados na Educação Pública* utilizando as ferramentas
apresentadas no curso.  


[Dados Salvador](https://novo.qedu.org.br/municipio/2927408-salvador) 

[Colégio Estadual Henriqueta Catharino](https://novo.qedu.org.br/escola/29192790-ee-colegio-estadual-henriqueta-martins-catharino/)

[Colégio Estadual Ypiranga](https://novo.qedu.org.br/escola/29182182-ee-colegio-estadual-ypiranga-educacao-integral/)  

[Colégio Estadual Deputado Manoel Novaes](https://novo.qedu.org.br/escola/29182131-ee-colegio-estadual-deputado-manoel-novaes/)

[Colégio Estadual da Bahia Central](https://novo.qedu.org.br/escola/29182123-ee-colegio-estadual-da-bahia-central/)

[Colégio Estadual Mário Costa Neto](https://novo.qedu.org.br/escola/29193699-ee-colegio-estadual-mario-costa-neto/)

[Escola Municipal Cidade Jequié](https://novo.qedu.org.br/escola/29190061-escola-municipal-cidade-de-jequie/)


## Instalações
Por favor, para facilitar o andamento do curso instalar previamente
os seguintes softwares indicados nas subseções a seguir.

### Vscode e Colab 

Instalar o [Vscode](https://code.visualstudio.com/Download) 

Acessar [Google Colaboratory - Colab](https://colab.research.google.com/) 

### Git e GitHub 

O primeiro passo para utilizar o Git é realizar sua instalação 
 por meio do link [Download Git](https://git-scm.com/downloads). 

### R e Rstudio

1. [Downlaod R](https://cran.r-project.org/bin/windows/base/)
- Instalação do R
2. [Download Rstudio](https://www.rstudio.com/products/rstudio/download/)
- Instalaçao do Rstudio


### Instalação MySQL 

1. [Download MySQL](https://dev.mysql.com/downloads/installer/)
2. [Instalação *MySQL Workbench*](https://dev.mysql.com/downloads/workbench/) 
3. [Cheat sheet](https://www.mysqltutorial.org/mysql-cheat-sheet.aspx)
